import type { Metadata } from "next";
import { alikeAngular } from "@/public/fonts";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full`}>
      <body className={`${alikeAngular.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
