import type { Metadata } from "next";
import { alikeAngular } from "@/public/fonts";
import "../../../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <section className="dashboard-container">
        {children} 
      </section>
    );
}
