# Generated by Django 6.0.5 on 2026-05-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('strength', models.FloatField()),
                ('inteligence', models.FloatField()),
                ('charisma', models.FloatField()),
                ('exp', models.FloatField()),
                ('level', models.IntegerField()),
                ('user_class', models.CharField(max_length=64)),
                ('user_hp', models.IntegerField()),
            ],
        ),
    ]
