# Generated by Django 6.0.5 on 2026-05-08 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duties',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
