# Generated by Django 6.0.5 on 2026-05-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bosses',
            fields=[
                ('boss_id', models.AutoField(primary_key=True, serialize=False)),
                ('boss_hp', models.IntegerField()),
                ('weakness', models.CharField()),
                ('boss_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentFight',
            fields=[
                ('fight_id', models.AutoField(primary_key=True, serialize=False)),
                ('seconds_left', models.IntegerField()),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentFight', to='core.bosses')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentFight', to='core.users')),
            ],
        ),
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('duty_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=7000)),
                ('strength', models.FloatField(default=0.0)),
                ('intelligence', models.FloatField(default=0.0)),
                ('charisma', models.FloatField(default=0.0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='core.users')),
            ],
        ),
    ]
