# Generated by Django 6.0.5 on 2026-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bosses_currentfight_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='duties',
            name='status',
            field=models.CharField(default='Active', max_length=64),
        ),
    ]
