# Generated by Django 6.0.5 on 2026-05-08 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_duties_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='duties',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
