# Generated by Django 6.0.5 on 2026-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_duties_deadline_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
