# Generated by Django 6.0.5 on 2026-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosses',
            name='boss_hp',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='bosses',
            name='boss_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='bosses',
            name='weakness',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='currentfight',
            name='seconds_left',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='duties',
            name='description',
            field=models.CharField(default=None, max_length=7000),
        ),
        migrations.AlterField(
            model_name='users',
            name='charisma',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='exp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='inteligence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='strength',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_hp',
            field=models.IntegerField(default=100),
        ),
    ]
