# Generated by Django 6.0.5 on 2026-05-08 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bosses_boss_hp_alter_bosses_boss_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyResetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('last_reset_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('habit_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default=None, max_length=7000)),
                ('strength', models.FloatField(default=0.0)),
                ('intelligence', models.FloatField(default=0.0)),
                ('charisma', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Active', max_length=64)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='core.users')),
            ],
        ),
    ]
