# Generated by Codex on 2026-05-09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_dailyresetstate_habits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duties",
            name="deadline",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
