# Generated by Django 6.0.5 on 2026-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_duties_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
