# Generated by Django 6.0.5 on 2026-05-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentfight',
            name='current_boss_hp',
            field=models.IntegerField(default=None),
        ),
    ]
