# Generated by Codex on 2026-05-10

import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_currentfight_current_boss_hp"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentfight",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="currentfight",
            name="ends_at",
            field=models.DateTimeField(default=core.models.default_fight_ends_at),
        ),
    ]
